blank_issues_enabled: false

issue_templates:
  - name: R 1.1 - 10 Aspetos Web
    description: requisito 1.1, 10 aspetos web
    file: ar_1_1.yml

  - name: R 1.2 - 10 Aspetos Web
    description: requisito 1.2, 10 aspetos web
    file: ar_1_2.yml

  - name: R 1.3 - 10 Aspetos Web
    description: requisito 1.3, 10 aspetos web
    file: ar_1_3.yml
